import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import About from '@/components/About'
import Experience from '@/components/Experience'
import Contact from '@/components/Contact'
import Home from '@/components/Home'
import Gallery from '@/components/Gallery'


const inter = Inter({ subsets: ['latin'] })

export default function Hero() {
  return (
    <>
      <Head>
        <title>Divyani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      <Header/>
      <Home/>
      <About/>
      <Experience/>
      <Gallery/>
      <Contact/>
      <Footer/>
     
    </>
  )
}
